apiVersion: v1
kind: Service
metadata:
  name: mytg-svc
  namespace: mytg
spec:
  type: NodePort
  selector:
    env: stage
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31001
